import { generateId } from '../utils'

export const dummyBatches = [
  { id: 'batch-1', name: 'Al-Falah 2018', year: '2018', description: 'Batch of 2018 graduates', memberCount: 45, joinCode: 'AF2018X' },
  { id: 'batch-2', name: 'An-Noor 2019', year: '2019', description: 'Batch of 2019 graduates', memberCount: 38, joinCode: 'AN2019Y' },
  { id: 'batch-3', name: 'Al-Huda 2020', year: '2020', description: 'Batch of 2020 graduates', memberCount: 52, joinCode: 'AH2020Z' },
  { id: 'batch-4', name: 'As-Salam 2021', year: '2021', description: 'Batch of 2021 graduates', memberCount: 41, joinCode: 'AS2021W' },
  { id: 'batch-5', name: 'Al-Iman 2022', year: '2022', description: 'Batch of 2022 graduates', memberCount: 33, joinCode: 'AI2022V' },
]

export const dummyMembers = [
  {
    id: 'mem-1',
    fullName: 'MOHAMMED ASHRAF K',
    email: 'ashraf@example.com',
    phone: '+919876543210',
    batchId: 'batch-1',
    batchName: 'Al-Falah 2018',
    district: 'Malappuram',
    membershipStatus: 'approved',
    paymentStatus: 'paid',
    posterStatus: 'ready',
    profilePhoto: null,
    registeredAt: '2026-06-10T08:30:00Z',
    approvedAt: '2026-06-12T14:00:00Z',
  },
  {
    id: 'mem-2',
    fullName: 'FATHIMA ZAHRA N',
    email: 'fathima@example.com',
    phone: '+919876543211',
    batchId: 'batch-2',
    batchName: 'An-Noor 2019',
    district: 'Kozhikode',
    membershipStatus: 'approved',
    paymentStatus: 'paid',
    posterStatus: 'ready',
    profilePhoto: null,
    registeredAt: '2026-06-08T10:15:00Z',
    approvedAt: '2026-06-10T09:30:00Z',
  },
  {
    id: 'mem-3',
    fullName: 'ABDUL RAHMAN M',
    email: 'rahman@example.com',
    phone: '+919876543212',
    batchId: 'batch-1',
    batchName: 'Al-Falah 2018',
    district: 'Thrissur',
    membershipStatus: 'pending',
    paymentStatus: 'unpaid',
    posterStatus: 'not_generated',
    profilePhoto: null,
    registeredAt: '2026-06-20T16:45:00Z',
    approvedAt: null,
  },
  {
    id: 'mem-4',
    fullName: 'AISHA SIDDIQUA P',
    email: 'aisha@example.com',
    phone: '+919876543213',
    batchId: 'batch-3',
    batchName: 'Al-Huda 2020',
    district: 'Kannur',
    membershipStatus: 'pending',
    paymentStatus: 'paid',
    posterStatus: 'not_generated',
    profilePhoto: null,
    registeredAt: '2026-06-19T12:00:00Z',
    approvedAt: null,
  },
  {
    id: 'mem-5',
    fullName: 'IBRAHIM KHALEEL T',
    email: 'ibrahim@example.com',
    phone: '+919876543214',
    batchId: 'batch-2',
    batchName: 'An-Noor 2019',
    district: 'Ernakulam',
    membershipStatus: 'approved',
    paymentStatus: 'paid',
    posterStatus: 'generating',
    profilePhoto: null,
    registeredAt: '2026-06-15T09:20:00Z',
    approvedAt: '2026-06-17T11:00:00Z',
  },
  {
    id: 'mem-6',
    fullName: 'MARIAM BEEVI S',
    email: 'mariam@example.com',
    phone: '+919876543215',
    batchId: 'batch-4',
    batchName: 'As-Salam 2021',
    district: 'Palakkad',
    membershipStatus: 'rejected',
    paymentStatus: 'unpaid',
    posterStatus: 'not_generated',
    profilePhoto: null,
    registeredAt: '2026-06-18T14:30:00Z',
    approvedAt: null,
  },
  {
    id: 'mem-7',
    fullName: 'YUSUF ALI K',
    email: 'yusuf@example.com',
    phone: '+919876543216',
    batchId: 'batch-3',
    batchName: 'Al-Huda 2020',
    district: 'Wayanad',
    membershipStatus: 'pending',
    paymentStatus: 'unpaid',
    posterStatus: 'not_generated',
    profilePhoto: null,
    registeredAt: '2026-06-21T08:00:00Z',
    approvedAt: null,
  },
  {
    id: 'mem-8',
    fullName: 'SAFIYA BEGUM R',
    email: 'safiya@example.com',
    phone: '+919876543217',
    batchId: 'batch-5',
    batchName: 'Al-Iman 2022',
    district: 'Kollam',
    membershipStatus: 'approved',
    paymentStatus: 'verified',
    posterStatus: 'ready',
    profilePhoto: null,
    registeredAt: '2026-06-05T11:45:00Z',
    approvedAt: '2026-06-07T10:15:00Z',
  },
  {
    id: 'mem-9',
    fullName: 'HASAN FAROOQ M',
    email: 'hasan@example.com',
    phone: '+919876543218',
    batchId: 'batch-1',
    batchName: 'Al-Falah 2018',
    district: 'Thiruvananthapuram',
    membershipStatus: 'pending',
    paymentStatus: 'paid',
    posterStatus: 'not_generated',
    profilePhoto: null,
    registeredAt: '2026-06-22T07:30:00Z',
    approvedAt: null,
  },
  {
    id: 'mem-10',
    fullName: 'NOORA FATHIMA H',
    email: 'noora@example.com',
    phone: '+919876543219',
    batchId: 'batch-4',
    batchName: 'As-Salam 2021',
    district: 'Idukki',
    membershipStatus: 'approved',
    paymentStatus: 'paid',
    posterStatus: 'ready',
    profilePhoto: null,
    registeredAt: '2026-06-01T13:00:00Z',
    approvedAt: '2026-06-03T15:30:00Z',
  },
]

export const dummyUsers = {
  admin: {
    id: 'user-admin',
    fullName: 'ADMIN USER',
    email: 'admin@aalia.org',
    role: 'admin',
    batchId: null,
    phone: '+919000000001',
    district: 'Malappuram',
  },
  batchAdmin: {
    id: 'user-batch-admin',
    fullName: 'BATCH ADMIN',
    email: 'batchadmin@aalia.org',
    role: 'batch_admin',
    batchId: 'batch-1',
    batchName: 'Al-Falah 2018',
    phone: '+919000000002',
    district: 'Kozhikode',
  },
  member: {
    id: 'mem-1',
    fullName: 'MOHAMMED ASHRAF K',
    email: 'ashraf@example.com',
    role: 'member',
    batchId: 'batch-1',
    batchName: 'Al-Falah 2018',
    phone: '+919876543210',
    district: 'Malappuram',
    membershipStatus: 'approved',
    paymentStatus: 'paid',
    posterStatus: 'ready',
    registeredAt: '2026-06-10T08:30:00Z',
    approvedAt: '2026-06-12T14:00:00Z',
  },
}

export function getStats() {
  const total = dummyMembers.length
  const pending = dummyMembers.filter((m) => m.membershipStatus === 'pending').length
  const approved = dummyMembers.filter((m) => m.membershipStatus === 'approved').length
  const rejected = dummyMembers.filter((m) => m.membershipStatus === 'rejected').length
  const paid = dummyMembers.filter((m) => m.paymentStatus === 'paid' || m.paymentStatus === 'verified').length
  return { total, pending, approved, rejected, paid }
}
